### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by XiaoXiaoZhiWei** [sqaiyan/NeteaseMusicWxMiniApp#1]
Uncaught Error: module "utils/bsurl.js" is not defined

**Comment by XiaoXiaoZhiWei** [comment]
是安装报错 缺少文件

**Comment by yaoshanliang** [comment]
对的 怎么解决？

**Comment by sqaiyan** [comment]
后台node源码已经放出来了，可以自己部署一下，缺失的这个文件就是我的服务器地址，之前被使用过多被网易云封了ip。换了同事的vps才可以的。自己部署后加上自己的服务器地址就可以 了 @zhongguoming @yaoshanliang
