### ISSUE TITLE
接口有问题

### ISSUE THREAD

**Issue by kitchunwu** [sqaiyan/NeteaseMusicWxMiniApp#11]
Request URL:http://localhost:3000/banner?cookie=
Request Method:GET
Status Code:404 Not Found
Remote Address:[::1]:3000

**Comment by sqaiyan** [comment]
文件已上传 更新下bsurl.js即可，你写这个少了一个路径而已，注意后端哪里有个v1

**Comment by kitchunwu** [comment]
感谢了，还有一个小问题，你能解决小程序（IOS端）animation-play-state的问题么，就是黑胶唱片在播放或暂停会卡顿

**Comment by sqaiyan** [comment]
@wuchunkit 我这出现的问题是无法暂停。我也不知道啥问题 可能就微信上x5bug什么的，一直想着解决但也拖到现在也不想动。你自己试试有什么方法吧。github也有好多这种动画的，我也没有试别人的方法。你可以找找看
