### ISSUE TITLE
我想问问mv播放不出来，总是显示这样子和这样一段错误代码，请问怎么解决

### ISSUE THREAD

**Issue by meidawei** [sqaiyan/NeteaseMusicWxMiniApp#16]
错误代码：
VM1169:2 Failed to load media http://v4.music.126.net/20180209161133/edbfcc8020033eb0e384fbfa10f221ee/web/cloudmusic/IiAxIDJkNiAwJjEwMTAiMQ==/mv/428018/8f95e751fa0a4c6feb905c813d5b83f7.mp4
the server responded with a status of 403 (HTTP/1.0 403 Forbidden) 
From server 183.236.10.87
请问是不是下载失败或者node后台出了问题

**Comment by sqaiyan** [comment]
[这里](https://github.com/sqaiyan/NeteaseMusicWxMiniApp/issues/18)
