### ISSUE TITLE
手机邮箱两个都登陆不上楼主是否开源的不完善

### ISSUE THREAD

**Issue by MISTwei** [sqaiyan/NeteaseMusicWxMiniApp#17]

**Comment by sqaiyan** [comment]
邮箱应该不行了，官网参数应该改了，手机我这一直都可以，你可以直接启动后台接口服务调用接口试试，如果可以应该是小程序代码的问题。你这只说不能登，没法判断哪里有问题

**Comment by MISTwei** [comment]
![snipaste_20180305_110721](https://user-images.githubusercontent.com/30832926/36955963-869421da-2066-11e8-8e5f-81098d616e6e.png)

**Comment by sqaiyan** [comment]
![image](https://user-images.githubusercontent.com/4329927/36956059-222366a6-2067-11e8-86d1-bf2bb08cdf70.png)

**Comment by MISTwei** [comment]
能加个联系方式吗有点问题想请教一下
