### ISSUE TITLE
小程序的MV无法播放

### ISSUE THREAD

**Issue by meidawei** [sqaiyan/NeteaseMusicWxMiniApp#18]
小程序的MV无法播放，一时间我也看不出是什么原因，请问作者可以解答一下吗

**Comment by sqaiyan** [comment]
mv播放地址不能直接用官网的地址，需要自己node层代理下，可以看我vue项目那个mv文件。
![image](https://user-images.githubusercontent.com/4329927/37698429-e4c643e6-2d1d-11e8-8db2-cc234fcc72fc.png)

自己改下吧，如果node项目教老，记得更新下node项目的代码
