### ISSUE TITLE
评论的URL好像有问题

### ISSUE THREAD

**Issue by meidawei** [sqaiyan/NeteaseMusicWxMiniApp#19]
今晚发现歌曲评论都看不了了，不知道是不是URL出问题了

**Comment by sqaiyan** [comment]
我本地测是正常的。你那估计是访问过于频繁造成的。可以过会重启下服务端就可以了。很多接口都是有访问次数监控的（目前遇到过有评论，歌单，搜索，登录）。过于频繁就不能正常返回数据了。
