### ISSUE TITLE
什么时候增加收藏功能

### ISSUE THREAD

**Issue by meidawei** [sqaiyan/NeteaseMusicWxMiniApp#20]
网上API已经能找到收藏的URL了，不过我实现还是有点问题，不知道你什么时候有空实现一下我学习一下，
https://github.com/Binaryify/NeteaseCloudMusicApi

**Comment by sqaiyan** [comment]
可以看我那个vue项目，都差不多的。有收藏电台和歌手的。歌单的好像麻烦点（要走新建歌单之类的接口）
