### ISSUE TITLE
小程序在播放音乐的时候，点击播放MV，音乐不会自动暂停

### ISSUE THREAD

**Issue by meidawei** [sqaiyan/NeteaseMusicWxMiniApp#23]
小程序在播放音乐的时候，再点击播放MV，音乐不会自动暂停，而是和MV一起播放，在哪里可以设置播放MV时候前面播放的音乐自动暂停？？

**Comment by sqaiyan** [comment]
是的没有做这个，可以在进入到mv页面时候直接调用微信的暂停背景音乐播放事件即可。或者app.js里面有个preplay方法。退出mv要继续播放的话还要记录之前是不是正在播放被mv页面暂停过，是的话再继续播放。
