### ISSUE TITLE
登录账户密码是什么啊

### ISSUE THREAD

**Issue by dzyook** [sqaiyan/NeteaseMusicWxMiniApp#27]
登录账户密码是什么啊

**Comment by sqaiyan** [comment]
自己的网易云音乐账户名密码

**Comment by AprilTong** [comment]
你好 我用自己的网易云账户登录提示code undefined  
![image](https://user-images.githubusercontent.com/24354441/44297524-aa2c6400-a305-11e8-8b49-500b1c5955dd.png)

**Comment by oneonethreebinbin** [comment]
登录账号和密码是什么啊？大哥
