### ISSUE TITLE
不在合法域名请求内

### ISSUE THREAD

**Issue by MengpingZZ** [sqaiyan/NeteaseMusicWxMiniApp#31]
大佬，想问问是服务器关了吗？现在无法使用后台数据，登陆页面请求运行后，显示  http://localhost:3000 不在以下 request 合法域名列表中，

**Comment by sqaiyan** [comment]
下载文档里写的node服务端项目，启动，即可开启接口服务，合法域名问题要在小程序开发工具中设置不校验域名
