### ISSUE TITLE
调试中的两个小问题

### ISSUE THREAD

**Issue by chengithubcom** [sqaiyan/NeteaseMusicWxMiniApp#4]
首先感谢您的分享.
在调试学习过程中发现三个小问题,特意来请教一下.
一、app.wxss中的样式.page-body-form有两个width: 100%; 此问题会导致后续的样式无法加载(在我这是这样的.)
二、app.json中加载了一个页面page/component/recsongs/index,但2017年1月18日下载的包里不存在.
三、底部导航条中,我的音乐链接为page/component/index,但2017年1月18日下载的包里也不存在.

再次感谢您的分享, 界面很酷~~~~~   学习中

**Comment by sqaiyan** [comment]
1,哪里不对改哪里
2，还在开发中，报错就删掉
3，不确定会不会做这个，后面看接口能不能找到，目前只是仿样子都显示。

代码很乱，将就着看吧。

**Comment by chengithubcom** [comment]
好的. 多谢
